name: build
on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

  workflow_dispatch:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.GitVersion.outputs.MajorMinorPatch }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.5
      with:
        versionSpec: '5.x'

    - name: GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.5
      id: GitVersion

  build-and-publish:
    name: Build & Publish Docker Image To Docker Hub
    runs-on: ubuntu-latest
    needs: get-version
    steps:
    - uses: actions/checkout@v2
    
    - name: Run CI test 
      run: |
        docker-compose up --build
        go test ./... -tags=e2e -v

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eibayan/mygo:$(date +%s)

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      if: github.ref == 'refs/heads/main'
      with:
        name: eibayan/mygo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  trigger-dev-deploy:
    name: Trigger Dev Deployment 
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/main'
    needs: get-version
    steps:
    - name: Deploy Dev Input
      id: DeployDevInput
      run: |
        echo ::set-output name=ref_input::'{ "ref": "${{ needs.get-version.outputs.version }}" }'
      env:
        version: ${{ needs.get-version.outputs.version }}

    - name: Deploy To Dev
      if: github.ref == 'refs/heads/main'
      id: deploy-to-dev
      uses: benc-uk/workflow-dispatch@v1
      with:
        token: ${{ secrets.CI_GITHUB_TOKEN }}
        workflow: deploy dev
        inputs: ${{ steps.DeployDevInput.outputs.ref_input }}