name: deploy dev

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GIT Release Tag'
        required: true

env:
  AWS_ACCOUNT: "123456789"
  REGION: "ap-southeast-2"
  CDK_ENV: "dev"
  ENVIRONMENT: "dev"
  IMAGE_ID: "eibayan/mygo"
  IMAGE_TAG: "latest"
  

jobs:
  startdeployment:
    name: Signal Deployment Started
    runs-on: ubuntu-latest

    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        bash: |
          echo "TODO: Work in progress..."